---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'

Injector:
  WebserviceAuthenticator:
    properties:
      allowPublicAccess: 1
---
Only:
  environment: 'live'
---
FilesystemPublisher:
  static_base_url: 'http://www-carot.us.melle.io/'
---
Name: mysiteconfig_redirector
After: 'staticpublishqueue/*'
---
RedirectorPage:
  extensions:
    - PublishableRedirectorPage
---
Name: mysiteconfig_staticpublishqueue
After: 'staticpublishqueue/*','#mysiteconfig_redirector'
---
SiteTree:
  extensions:
    - PublishableSiteTree
    - SiteTreePublishingEngine
    - FilesystemPublisher('cache', 'html')

